version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
